### ISSUE TITLE
Progress info broken ?

### ISSUE THREAD

**Issue by qgrosperrin** [iomoath/SharpSpray#1]
Hi, thanks for your tool.

Is the tool supposed to write to console regularly showing "X attempts were made so far." ?
From what I experienced it's only displayed when all users have been tried, so when you run an attack against a high number of users it feels like there is no progress at all giving you the impression that it's not working (even with verbose flag enabled). 

Sample command used (via Cobalt Strike) 
```execute-assembly SharpSpray.exe -u users.txt -p Winter2022! -x -s 1 -z -v -o spraying-output.txt --Force
[*] The domain password policy observation window is set to 0 minutes.
[*] Setting a 0 minute wait in between sprays.
[*] WARNING - Be very careful not to lock out accounts with the -k --pl option!
[*] Password spraying has begun with 1 passwords
[*] This might take a while depending on the total number of users & passwords.
[*] Now trying password Winter2022! against 47243 users. Current time is 2021-11-24 1:13:41 PM
```
(I know it's probably not wise to target that many users, but I'm not worried about stealth here)

**Comment by iomoath** [comment]
Hello, Thanks for reporting this. I will fix it in the upcoming release (expected 1-3 days)

**Comment by iomoath** [comment]
I pushed an update, Release V1.1
Use the switch -v to display verbose messages

![sharpspray_cs](https://user-images.githubusercontent.com/35432988/143491410-87180f9d-fcb5-4267-b8d0-09265cf48c82.png)
